### ISSUE TITLE
Please remove the requirement that webDAV username must be email

### ISSUE THREAD

**Issue by fjxhkj** [Offerel/SyncMarks-Extension#18]
Thank you for sharing such a good tool!
Please remove the requirement that webDAV username must be email.
Some self-built WebDAV services do not require email as a user name.

**Comment by Offerel** [comment]
I will have a look in to that

**Comment by Offerel** [comment]
Do you have a testserver where the username is not an e-mail address? According to my investigation, it should work. There should be no requirement to enter an e-mail address.

**Comment by Offerel** [comment]
Close this issue as of no response as of yet
