### ISSUE TITLE
I have a problem with login.

### ISSUE THREAD

**Issue by PainlessDestiny** [Offerel/SyncMarks-Extension#19]
I can not log in with jianguoyun on kiwi, Login failed: Status: 501
![Screenshot_20201123-205337](https://user-images.githubusercontent.com/31487161/99964724-6123af80-2d59-11eb-9a4e-ade5b2cc4aaf.png)

**Comment by PainlessDestiny** [comment]
yandex disk also can not log in , Login failed: Status: 405

**Comment by Offerel** [comment]
Error 501 means, that the method is not implemented at server level. There is nothing i can do against that. Its a server side issue. As you are using WebDAV, this means the used WebDAV implementation does not use the standard DAV methods. Please ask the admin at the server.

Error 405 is something similar. In this case the addon uses a simple GET request to try to login to the server with basic auth method. It seems that this isnt either not implemented at your target server or implemented in a wrong way. Please ask the server admin.

**Comment by Offerel** [comment]
Close this issue as of no response as of yet
