### ISSUE TITLE
Opening addon preferences tries to open changelog.md

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Extension#23]
Hi,

As a postit for later ;)

Popup open's in amo's and dev's versions. 

K.

**Comment by Offerel** [comment]
the changelog is opened as the third tab in preferences. it should not be opened as a separate page or popup.

**Comment by kayceegb** [comment]
To be more precise it's the popup that ask what I want to do with the file "Open/save/...". Like if it was an ordinary file to download. 

I see in options the third tab but empty. :/

**Comment by Offerel** [comment]
In that case, this is an FF issue. It works correctly with actual FF versions and other browsers. If this occurs also with newer FF version, you can open a bug report at Mozilla.

**Comment by kayceegb** [comment]
I see. I hope I will be able to test with a newer version soon.

**Comment by Offerel** [comment]
Cant reproduce this, also not with FF 60.2.1 ESR (installed as portable, if this makes a difference)

**Comment by kayceegb** [comment]
I think I have found a trick/workaround/fix. Don't know how to call that. 

When the addon wants to open changelog.md, it is seen as text/markdown, and FF don't recognizes this. So it opens the dialog to save/open with/... 

At this reply https://superuser.com/questions/696361/how-to-get-the-markdown-viewer-addon-of-firefox-to-work-on-linux/1175837#1175837 , there is a solution to "force" .md files as plain/text.

Once I put this
```
<?xml version="1.0"?>
<mime-info xmlns='http://www.freedesktop.org/standards/shared-mime-info'>
  <mime-type type="text/plain">
    <glob pattern="*.md"/>
  </mime-type>
</mime-info>
```
in 

    ~/.local/share/mime/packages/text-markdown.xml

and reload mime database with

    update-mime-database ~/.local/share/mime

followed by a firefox restart, the dialog does not open anymore and the third tab of addon's preferences has the changelog.

**Comment by Offerel** [comment]
OK, this is no html standard, but maybe using `<iframe class="cframe" type="text/plain" src="../CHANGELOG.md"></iframe>`  in options.html, instead of  `<iframe class="cframe" src="../CHANGELOG.md"></iframe>`, will do the same thing. At least it didnt produce an error in Windows.

Or as an alternative `<embed height="100%" class="cframe" src="../CHANGELOG.md" type="text/plain">`. Specifying the mime type in embed tag is indeed a standard, but i don't know, if OS or FF settings will overwrite this.

**Comment by Offerel** [comment]
Since i have currently no Linux OS installed, can you please the above variants? 

I have additionally another option, but this can lead to other complications. So i would avoid that, if possible.

**Comment by kayceegb** [comment]
I am currently testing. The modification to iframe does not seem to have any effect. The dialog opens. 

For the other I can just replace iframe by embed ?

**Comment by Offerel** [comment]
I try another one after the lunch and make a separate branch for this.

**Comment by kayceegb** [comment]
Is it really important for you to have changelog here ? 

Can't you change the changelog tab to someting like "About" and in this tab put some informations, maybe basic, with links to home, changelog, etc, ... ? 

Wouldn't it be sufficient ? And that would prevent trying to fix this for everyone.

**Comment by Offerel** [comment]
Yes this can be an option, but i didn't like that. The reason for dislike is the translation to other languages. In this case the text for this tab has to translated in all supported languages. Currently there are only 2 of them, but its more work for every potential translator.

I have created now new branch. where i read the text content to a variable and display that on the tab. This can work better. You can try that if you want.

**Comment by kayceegb** [comment]
Ok for the translation. It is a valid reason. 

For your change, after reverting the trick, that works. 
It is another thing I wanted to propose to you, a little bit differently. The idea was to insert here last 10 or 15 changes and add a lind to the full changelog. At this time if FF's or other browser's dialog opens, it is less problematic. 

Like it is now, I see a little "wait time" of 1-2 secs at first? tab opening. Next switchings are ok.

**Comment by Offerel** [comment]
There can be a little waiting time or delay, since the JS does some sort of local http request (without a http server). This is actually called, when you click the tab for the first time.

I can try to move this call to the opening of the settings page itself. So it's loaded asynchronous at opening the page and displayed immediately when you click the tab. 

For simplicity, I use currently the same changelog.md file for multiple purpose. Before I forget to add the changelog completely 😀...

**Comment by kayceegb** [comment]
I suppose that should be fine like it is now. You don't open preferences so often, and yet less often changelog.
