### ISSUE TITLE
Clear logs in log tab

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Extension#27]
Hi,

Sometimes I need to clear the logs from the log tab. I don't see an easy way to do that. I have to remove and readd the addon. Is it possible to add a clear log button ?

And additionnal question, what is the arrow in log tab for ? 

K.

**Comment by Offerel** [comment]
I can add such a function. With the arrow, you can save the logfile to you hdd.

**Comment by kayceegb** [comment]
That would be great!

I thought that the arrow is to download but as it does not seem to do anything for me I asked. Does it work for you ? I tried with ff68esr and 78esr.

**Comment by Offerel** [comment]
Code was commented out, since there was an open bug in Firefox. This seems to be solved at least in Firefox 83 release. This and the clearing the log is now in commit [26dcff9](https://github.com/Offerel/SyncMarks-Extension/commit/26dcff9f135ed4ecd238e7ac6084aa40cea18bda)

**Comment by kayceegb** [comment]
Both are working for me with ff 68esr
